# Generated by Django 4.2.6 on 2023-10-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillHive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillhive',
            name='email',
        ),
        migrations.AddField(
            model_name='skillhive',
            name='cover_photo',
            field=models.ImageField(default=None, upload_to='course_covers/'),
        ),
        migrations.AddField(
            model_name='skillhive',
            name='description',
            field=models.TextField(default=None, max_length=10000),
        ),
        migrations.AddField(
            model_name='skillhive',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
